# version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: anime_postgres
    restart: always
    environment:
      POSTGRES_USER: anime_user
      POSTGRES_PASSWORD: anime_pass
      POSTGRES_DB: anime_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./data/processed:/data/processed

  redis:
    image: redis:8
    container_name: anime_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: anime_api
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://anime_user:anime_pass@postgres:5432/anime_db
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/app

volumes:
  pgdata:
